apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard #kubectl get storageclass
  resources:
    requests:
      storage: 10Gi